# Generated by Django 5.2.14 on 2026-06-01 07:09

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('courses', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('gateway', models.CharField(choices=[('RAZORPAY', 'Razorpay'), ('STRIPE', 'Stripe'), ('PAYPAL', 'PayPal')], default='STRIPE', max_length=20)),
                ('payment_status', models.CharField(choices=[('PENDING', 'Pending'), ('SUCCESS', 'Success'), ('FAILED', 'Failed'), ('REFUNDED', 'Refunded')], db_index=True, default='PENDING', max_length=20)),
                ('transaction_id', models.CharField(blank=True, db_index=True, max_length=180)),
                ('order_id', models.CharField(db_index=True, max_length=180, unique=True)),
                ('currency', models.CharField(default='USD', max_length=3)),
                ('invoice_file', models.FileField(blank=True, null=True, upload_to='invoices/%Y/%m/')),
                ('gateway_response', models.JSONField(blank=True, default=dict)),
                ('payment_date', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payments', to='courses.course')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-payment_date'],
                'indexes': [models.Index(fields=['student', 'payment_status'], name='payments_pa_student_07071e_idx'), models.Index(fields=['gateway', 'payment_status'], name='payments_pa_gateway_a262ea_idx')],
            },
        ),
    ]
